# Generated by Django 6.0 on 2025-12-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image_url',
            field=models.ImageField(upload_to='packages/'),
        ),
    ]
