# Generated by Django 6.0 on 2025-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_popularpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpackage',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Fixed departure date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='hotel_category',
            field=models.CharField(blank=True, choices=[('3_star', '3 Star'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], max_length=20),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='meal_plan',
            field=models.CharField(blank=True, help_text='Breakfast / Lunch / Dinner', max_length=100),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='meals_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='offer_title',
            field=models.CharField(blank=True, help_text='Eg: Book 5 seats & get 5 bags free', max_length=200),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='places_covered',
            field=models.TextField(blank=True, help_text='Comma separated places list', null=True),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='room_type',
            field=models.CharField(blank=True, choices=[('common', 'Common Hall'), ('four_share', '4 Sharing'), ('double', 'Double Sharing')], max_length=20),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='sightseeing_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='tour_guide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popularpackage',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('ac_bus', 'AC Sleeper Bus'), ('pushback_bus', 'Pushback Bus'), ('train', 'Train')], max_length=20),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='is_bookable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='pax',
            field=models.PositiveIntegerField(help_text='Number of people in a group'),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='region',
            field=models.CharField(help_text='South India, North India, International etc.', max_length=100),
        ),
    ]
