# Generated by Django 6.0 on 2026-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_popularpackage_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='packageimage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='popularpackage',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='popularpackage',
            name='meal_plan',
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='offer_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='pax',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='places_covered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='popularpackage',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
